languageCode = "en-us"
title = "Spring Cloud Netflix: Circuit Breaking Metric Aggregation"
theme = "hugo-theme-bootie-docs"
copyright = "Â© Copyright Pivotal. All rights reserved."

[params]
  basedir = "/spring-cloud-services-spring-cloud-netflix-circuit-breaking-metric-aggregation"
  mainMenu=["goals", "setup", "instructions", "resources"]
  noCategoryLink = true
  description = ""
